Server:
  RunMode: debug
  HttpPort: 9000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  NormalUserDeviceUplimit: 20
  VipUserDeviceUplimit: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
Database:
  DBType: mysql
  Username: root
  Password: admin
  Host: 127.0.0.1:3306
  DBName: iot_service
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
